name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  VITE_EMAILJS_SERVICE_ID: service_wrmc1ui
  VITE_EMAILJS_TEMPLATE_ID: template_oo6sj7l
  VITE_EMAILJS_PUBLIC_KEY: CTUNxPC5QKaMYmT3K

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      # Create .env file with secrets
      - name: Create .env file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${VITE_EMAILJS_SERVICE_ID}" > .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${VITE_EMAILJS_TEMPLATE_ID}" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY=${VITE_EMAILJS_PUBLIC_KEY}" >> .env
          cat .env
        
      - name: Build
        run: npm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
          VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
          VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
        
      # Replace environment variables in build output
      - name: Process environment variables
        run: |
          echo "Processing environment variables in build files..."
          node env.js
        env:
          VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
          VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
          VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
        
      # Verify environment variables were correctly injected
      - name: Verify build output
        run: |
          echo "Checking for EmailJS variables in build output..."
          grep -r "service_wrmc1ui" dist/ || echo "Service ID not found in build output (should find it)"
          grep -r "template_oo6sj7l" dist/ || echo "Template ID not found in build output (should find it)"
          grep -r "CTUNxPC5QKaMYmT3K" dist/ || echo "Public Key not found in build output (should find it)"
          
      # Create required files for GitHub Pages
      - name: Configure GitHub Pages specific files
        run: |
          touch dist/.nojekyll
          cp public/_headers dist/ || echo "No _headers file found"
          
      - name: Deploy with gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist